##############################################################
# WaveLobby                                                  #
# Created by LionGaming_95                                   #
# Development begin on 01.05.21                              #
# Development Finished on ~                                  #
# Support on Discord http://discord.aniheaven.net/           #
# This system has a Copyright protection by LionGaming_95    #
# Minecraft version tested on 1.8 and 1.16.5                 #
##############################################################
Lobby:
  Prefix: "&8[&3Wave§bLobby&8] &f"
  AllowJoinMessage: true
  AllowQuitMessage: true
  DoppleJumpHeigh: 1.5
##############################################################
Messages:
  JoinMessage: "&a%player% &ebetrat den Server!"
  QuitMessage: "&c%player% &4Verließ den Server!"
##############################################################
MySQL:
  Username: "netzwerk"
  Password: "UE8xiWZ1UCJvCuYd"
  Host: "localhost"
  Datenbank: "netzwerk"
  Port: 3306
##############################################################